### ISSUE TITLE
Packaging my game is not working, is it possible I used too much space or something?

### ISSUE THREAD

**Issue by capitjeff21** [Mittagskogel/Sulfurous#119]
https://scratch.mit.edu/projects/217841350
https://newton.nes.aau.at/~sulfurous/#217841350

```
Error: HTTP 404: Not Found
    at XMLHttpRequest.xhr.onload (https://sulfurous.aau.at/js/phosphorus.js:463:23)
```

**Comment by htmlgames** [comment]
This isn't working because the app.html url (with game id) is not pointing at the legacy folder like so:

FAILS:
https://sulfurous.aau.at/html/app.html?id=187392999&turbo=false&full-screen=false&aspect-x=&aspect-y=&resolution-x=480&resolution-y=360

WORKS:
https://sulfurous.aau.at/legacy/html/app.html?id=187392999&turbo=false&full-screen=false&aspect-x=&aspect-y=&resolution-x=480&resolution-y=360

so in line 285 of index.html

packageLink.href = P.player.projectId ? 'https://sulfurous.aau.at/html/app.html?id=' + P.player.projectId +

change this to:

packageLink.href = P.player.projectId ? 'https://sulfurous.aau.at/legacy/html/app.html?id=' + P.player.projectId +

**Comment by FRALEXAlexander** [comment]
see #122
